const minecraftItems = {
    // Tools
    tools: [
        { id: 'WOODEN_SWORD', text: 'Wooden Sword' },
        { id: 'STONE_SWORD', text: 'Stone Sword' },
        { id: 'IRON_SWORD', text: 'Iron Sword' },
        { id: 'GOLDEN_SWORD', text: 'Golden Sword' },
        { id: 'DIAMOND_SWORD', text: 'Diamond Sword' },
        { id: 'NETHERITE_SWORD', text: 'Netherite Sword' },
        { id: 'WOODEN_AXE', text: 'Wooden Axe' },
        { id: 'STONE_AXE', text: 'Stone Axe' },
        { id: 'IRON_AXE', text: 'Iron Axe' },
        { id: 'GOLDEN_AXE', text: 'Golden Axe' },
        { id: 'DIAMOND_AXE', text: 'Diamond Axe' },
        { id: 'NETHERITE_AXE', text: 'Netherite Axe' },
        { id: 'WOODEN_PICKAXE', text: 'Wooden Pickaxe' },
        { id: 'STONE_PICKAXE', text: 'Stone Pickaxe' },
        { id: 'IRON_PICKAXE', text: 'Iron Pickaxe' },
        { id: 'GOLDEN_PICKAXE', text: 'Golden Pickaxe' },
        { id: 'DIAMOND_PICKAXE', text: 'Diamond Pickaxe' },
        { id: 'NETHERITE_PICKAXE', text: 'Netherite Pickaxe' },
        { id: 'WOODEN_SHOVEL', text: 'Wooden Shovel' },
        { id: 'STONE_SHOVEL', text: 'Stone Shovel' },
        { id: 'IRON_SHOVEL', text: 'Iron Shovel' },
        { id: 'GOLDEN_SHOVEL', text: 'Golden Shovel' },
        { id: 'DIAMOND_SHOVEL', text: 'Diamond Shovel' },
        { id: 'NETHERITE_SHOVEL', text: 'Netherite Shovel' },
        { id: 'WOODEN_HOE', text: 'Wooden Hoe' },
        { id: 'STONE_HOE', text: 'Stone Hoe' },
        { id: 'IRON_HOE', text: 'Iron Hoe' },
        { id: 'GOLDEN_HOE', text: 'Golden Hoe' },
        { id: 'DIAMOND_HOE', text: 'Diamond Hoe' },
        { id: 'NETHERITE_HOE', text: 'Netherite Hoe' },
        { id: 'FISHING_ROD', text: 'Fishing Rod' },
        { id: 'FLINT_AND_STEEL', text: 'Flint and Steel' },
        { id: 'SHEARS', text: 'Shears' },
        { id: 'BOW', text: 'Bow' },
        { id: 'CROSSBOW', text: 'Crossbow' },
        { id: 'TRIDENT', text: 'Trident' },
        { id: 'CARROT_ON_A_STICK', text: 'Carrot on a Stick' },
        { id: 'WARPED_FUNGUS_ON_A_STICK', text: 'Warped Fungus on a Stick' },
        { id: 'SHIELD', text: 'Shield' },
        { id: 'ELYTRA', text: 'Elytra' },
        { id: 'CLOCK', text: 'Clock' },
        { id: 'COMPASS', text: 'Compass' },
        { id: 'RECOVERY_COMPASS', text: 'Recovery Compass' },
        { id: 'SPYGLASS', text: 'Spyglass' },
        { id: 'LEAD', text: 'Lead' },
        { id: 'NAME_TAG', text: 'Name Tag' },
        { id: 'SADDLE', text: 'Saddle' }
    ],

    // Armor
    armor: [
        { id: 'LEATHER_HELMET', text: 'Leather Helmet' },
        { id: 'LEATHER_CHESTPLATE', text: 'Leather Chestplate' },
        { id: 'LEATHER_LEGGINGS', text: 'Leather Leggings' },
        { id: 'LEATHER_BOOTS', text: 'Leather Boots' },
        { id: 'CHAINMAIL_HELMET', text: 'Chainmail Helmet' },
        { id: 'CHAINMAIL_CHESTPLATE', text: 'Chainmail Chestplate' },
        { id: 'CHAINMAIL_LEGGINGS', text: 'Chainmail Leggings' },
        { id: 'CHAINMAIL_BOOTS', text: 'Chainmail Boots' },
        { id: 'IRON_HELMET', text: 'Iron Helmet' },
        { id: 'IRON_CHESTPLATE', text: 'Iron Chestplate' },
        { id: 'IRON_LEGGINGS', text: 'Iron Leggings' },
        { id: 'IRON_BOOTS', text: 'Iron Boots' },
        { id: 'GOLDEN_HELMET', text: 'Golden Helmet' },
        { id: 'GOLDEN_CHESTPLATE', text: 'Golden Chestplate' },
        { id: 'GOLDEN_LEGGINGS', text: 'Golden Leggings' },
        { id: 'GOLDEN_BOOTS', text: 'Golden Boots' },
        { id: 'DIAMOND_HELMET', text: 'Diamond Helmet' },
        { id: 'DIAMOND_CHESTPLATE', text: 'Diamond Chestplate' },
        { id: 'DIAMOND_LEGGINGS', text: 'Diamond Leggings' },
        { id: 'DIAMOND_BOOTS', text: 'Diamond Boots' },
        { id: 'NETHERITE_HELMET', text: 'Netherite Helmet' },
        { id: 'NETHERITE_CHESTPLATE', text: 'Netherite Chestplate' },
        { id: 'NETHERITE_LEGGINGS', text: 'Netherite Leggings' },
        { id: 'NETHERITE_BOOTS', text: 'Netherite Boots' },
        { id: 'TURTLE_HELMET', text: 'Turtle Helmet' }
    ],

    // Materials
    materials: [
        { id: 'DIAMOND', text: 'Diamond' },
        { id: 'GOLD_INGOT', text: 'Gold Ingot' },
        { id: 'IRON_INGOT', text: 'Iron Ingot' },
        { id: 'EMERALD', text: 'Emerald' },
        { id: 'NETHERITE_INGOT', text: 'Netherite Ingot' },
        { id: 'LEATHER', text: 'Leather' },
        { id: 'FEATHER', text: 'Feather' },
        { id: 'STRING', text: 'String' },
        { id: 'BLAZE_ROD', text: 'Blaze Rod' },
        { id: 'BONE', text: 'Bone' },
        { id: 'SLIME_BALL', text: 'Slime Ball' },
        { id: 'ENDER_PEARL', text: 'Ender Pearl' },
        { id: 'GHAST_TEAR', text: 'Ghast Tear' },
        { id: 'MAGMA_CREAM', text: 'Magma Cream' },
        { id: 'PHANTOM_MEMBRANE', text: 'Phantom Membrane' },
        { id: 'PRISMARINE_SHARD', text: 'Prismarine Shard' },
        { id: 'PRISMARINE_CRYSTALS', text: 'Prismarine Crystals' },
        { id: 'RABBIT_HIDE', text: 'Rabbit Hide' },
        { id: 'SCUTE', text: 'Scute' },
        { id: 'SHULKER_SHELL', text: 'Shulker Shell' },
        { id: 'TURTLE_EGG', text: 'Turtle Egg' },
        { id: 'COAL', text: 'Coal' },
        { id: 'CHARCOAL', text: 'Charcoal' },
        { id: 'LAPIS_LAZULI', text: 'Lapis Lazuli' },
        { id: 'QUARTZ', text: 'Quartz' },
        { id: 'AMETHYST_SHARD', text: 'Amethyst Shard' },
        { id: 'COPPER_INGOT', text: 'Copper Ingot' },
        { id: 'RAW_IRON', text: 'Raw Iron' },
        { id: 'RAW_GOLD', text: 'Raw Gold' },
        { id: 'RAW_COPPER', text: 'Raw Copper' },
        { id: 'CLAY_BALL', text: 'Clay Ball' },
        { id: 'BRICK', text: 'Brick' },
        { id: 'NETHER_BRICK', text: 'Nether Brick' },
        { id: 'PAPER', text: 'Paper' },
        { id: 'BOOK', text: 'Book' },
        { id: 'INK_SAC', text: 'Ink Sac' },
        { id: 'GLOW_INK_SAC', text: 'Glow Ink Sac' },
        { id: 'GUNPOWDER', text: 'Gunpowder' },
        { id: 'SUGAR', text: 'Sugar' },
        { id: 'EGG', text: 'Egg' },
        { id: 'HONEYCOMB', text: 'Honeycomb' },
        { id: 'HONEY_BOTTLE', text: 'Honey Bottle' },
        { id: 'NETHER_STAR', text: 'Nether Star' },
        { id: 'DRAGON_EGG', text: 'Dragon Egg' },
        { id: 'DRAGON_BREATH', text: 'Dragon Breath' },
        { id: 'HEART_OF_THE_SEA', text: 'Heart of the Sea' },
        { id: 'NAUTILUS_SHELL', text: 'Nautilus Shell' },
        { id: 'ECHO_SHARD', text: 'Echo Shard' },
        { id: 'DISC_FRAGMENT_5', text: 'Disc Fragment 5' }
    ],

    // Food
    food: [
        { id: 'APPLE', text: 'Apple' },
        { id: 'BREAD', text: 'Bread' },
        { id: 'COOKED_BEEF', text: 'Cooked Beef' },
        { id: 'COOKED_CHICKEN', text: 'Cooked Chicken' },
        { id: 'COOKED_MUTTON', text: 'Cooked Mutton' },
        { id: 'COOKED_PORKCHOP', text: 'Cooked Porkchop' },
        { id: 'COOKED_RABBIT', text: 'Cooked Rabbit' },
        { id: 'GOLDEN_APPLE', text: 'Golden Apple' },
        { id: 'MELON_SLICE', text: 'Melon Slice' },
        { id: 'PUMPKIN_PIE', text: 'Pumpkin Pie' },
        { id: 'SWEET_BERRIES', text: 'Sweet Berries' },
        { id: 'GLOW_BERRIES', text: 'Glow Berries' },
        { id: 'CHORUS_FRUIT', text: 'Chorus Fruit' },
        { id: 'DRIED_KELP', text: 'Dried Kelp' },
        { id: 'COOKIE', text: 'Cookie' },
        { id: 'CAKE', text: 'Cake' },
        { id: 'MUSHROOM_STEW', text: 'Mushroom Stew' },
        { id: 'BEETROOT_SOUP', text: 'Beetroot Soup' },
        { id: 'RABBIT_STEW', text: 'Rabbit Stew' },
        { id: 'SUSPICIOUS_STEW', text: 'Suspicious Stew' },
        { id: 'HONEY_BOTTLE', text: 'Honey Bottle' },
        { id: 'ROTTEN_FLESH', text: 'Rotten Flesh' },
        { id: 'SPIDER_EYE', text: 'Spider Eye' },
        { id: 'POISONOUS_POTATO', text: 'Poisonous Potato' },
        { id: 'POTATO', text: 'Potato' },
        { id: 'BAKED_POTATO', text: 'Baked Potato' },
        { id: 'CARROT', text: 'Carrot' },
        { id: 'GOLDEN_CARROT', text: 'Golden Carrot' },
        { id: 'BEETROOT', text: 'Beetroot' },
        { id: 'WHEAT', text: 'Wheat' },
        { id: 'SUGAR_CANE', text: 'Sugar Cane' },
        { id: 'BAMBOO', text: 'Bamboo' },
        { id: 'KELP', text: 'Kelp' },
        { id: 'SEA_PICKLE', text: 'Sea Pickle' },
        { id: 'CACTUS', text: 'Cactus' },
        { id: 'BROWN_MUSHROOM', text: 'Brown Mushroom' },
        { id: 'RED_MUSHROOM', text: 'Red Mushroom' },
        { id: 'CRIMSON_FUNGUS', text: 'Crimson Fungus' },
        { id: 'WARPED_FUNGUS', text: 'Warped Fungus' },
        { id: 'NETHER_WART', text: 'Nether Wart' },
        { id: 'CHORUS_FLOWER', text: 'Chorus Flower' },
        { id: 'CHORUS_PLANT', text: 'Chorus Plant' },
        { id: 'WEEPING_VINES', text: 'Weeping Vines' },
        { id: 'TWISTING_VINES', text: 'Twisting Vines' },
        { id: 'VINE', text: 'Vine' },
        { id: 'LILY_PAD', text: 'Lily Pad' },
        { id: 'SEAGRASS', text: 'Seagrass' },
        { id: 'TALL_SEAGRASS', text: 'Tall Seagrass' },
        { id: 'SEA_PICKLE', text: 'Sea Pickle' },
        { id: 'KELP', text: 'Kelp' },
        { id: 'DRIED_KELP_BLOCK', text: 'Dried Kelp Block' }
    ],

    // Blocks
    blocks: [
        { id: 'STONE', text: 'Stone' },
        { id: 'GRANITE', text: 'Granite' },
        { id: 'POLISHED_GRANITE', text: 'Polished Granite' },
        { id: 'DIORITE', text: 'Diorite' },
        { id: 'POLISHED_DIORITE', text: 'Polished Diorite' },
        { id: 'ANDESITE', text: 'Andesite' },
        { id: 'POLISHED_ANDESITE', text: 'Polished Andesite' },
        { id: 'GRASS_BLOCK', text: 'Grass Block' },
        { id: 'DIRT', text: 'Dirt' },
        { id: 'COARSE_DIRT', text: 'Coarse Dirt' },
        { id: 'PODZOL', text: 'Podzol' },
        { id: 'CRIMSON_NYLIUM', text: 'Crimson Nylium' },
        { id: 'WARPED_NYLIUM', text: 'Warped Nylium' },
        { id: 'COBBLESTONE', text: 'Cobblestone' },
        { id: 'OAK_PLANKS', text: 'Oak Planks' },
        { id: 'SPRUCE_PLANKS', text: 'Spruce Planks' },
        { id: 'BIRCH_PLANKS', text: 'Birch Planks' },
        { id: 'JUNGLE_PLANKS', text: 'Jungle Planks' },
        { id: 'ACACIA_PLANKS', text: 'Acacia Planks' },
        { id: 'DARK_OAK_PLANKS', text: 'Dark Oak Planks' },
        { id: 'CRIMSON_PLANKS', text: 'Crimson Planks' },
        { id: 'WARPED_PLANKS', text: 'Warped Planks' }
    ],

    // Get all items as a flat array
    getAllItems: function() {
        return [
            ...this.tools.map(item => ({ ...item, category: 'Tools' })),
            ...this.armor.map(item => ({ ...item, category: 'Armor' })),
            ...this.materials.map(item => ({ ...item, category: 'Materials' })),
            ...this.food.map(item => ({ ...item, category: 'Food' })),
            ...this.blocks.map(item => ({ ...item, category: 'Blocks' }))
        ];
    }
}; 